remote: true

experienceLevel:
  internship: true
  entry: true
  associate: true
  mid-senior level: true
  director: false
  executive: false

jobTypes:
  full-time: true
  contract: true
  part-time: false
  temporary: true
  internship: false
  other: false
  volunteer: true

date:
  all time: false
  month: false
  week: false
  24 hours: true

positions:
  - Software Test



locations:
  - Dallas
  - Vancouver
  - Surrey
  - Abu Dhabi

distance: 100

companyBlacklist:
  - Noir
  - Crossover
  - Xpertise Recruitment
  - Recruit
  - Recruiters
  - Staffing
  - Agency
  - Firm
  - Consultancy
  - Consultants
  - Talent
  - Talents
  - Services
  - CyberCoders
  - TekSystems
  - systems
  - system
  - solutions
  - tek
  - coder
  - Jobot
  - Digital Janet
  - Insight Global
  - Robert Half
  - XpertDirect
  - DCM Infotech Limited
  - HCLTech
  - Zortech Solutions
titleBlacklist:
  - Windows
  - Azure
  - C#
